image: maven:3.6.3-jdk-11

java:
  tags:
    - runner
  stage: test
  script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent compile test -Pdev sonar:sonar -Dsonar.projectKey=swe-Do-25 -Dsonar.projectName=swe-Do-25 -Dsonar.host.url=https://ec.cs.hm.edu/
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
